name: Sleep Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 22:00 ARG

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rama sleep
        uses: actions/checkout@v3
        with:
          ref: sleep

      - name: Instalar Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Autenticarse en Railway y hacer deploy
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway up
