name: Sleep Bot

on:
  schedule:
    - cron: '0 1 * * *'  # 22:00 Argentina / 01:00 UTC
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rama sleep
        uses: actions/checkout@v3
        with:
          ref: sleep

      - name: Instalar Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Hacer deploy a Railway (rama sleep)
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up
