name: Sleep Bot

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rama sleep
        uses: actions/checkout@v3
        with:
          ref: sleep

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Hacer deploy a Railway (rama sleep)
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --service gimnasio-bot
