name: Stop Bot

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Railway CLI
        run: npm install -g railway

      - name: Apagar el bot (railway down)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway down
