name: Wake Bot

on:
  schedule:
    - cron: '0 11 * * *' 
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rama main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Hacer deploy a Railway (rama main)
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --service gimnasio-bot
